# Generated by Django 4.0.1 on 2022-02-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatransactions',
            options={'ordering': ['-Timestamp']},
        ),
        migrations.AlterField(
            model_name='datatransactions',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
