# Generated by Django 4.0.1 on 2022-02-07 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_alter_datatransactions_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatransactions',
            name='Type',
        ),
        migrations.AddField(
            model_name='datatransactions',
            name='Credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datatransactions',
            name='To_wallet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='City',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='wallet',
            name='First_Name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='wallet',
            name='Gender',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='wallet',
            name='Last_Name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='wallet',
            name='Phone_number',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
