# Generated by Django 4.0.1 on 2022-02-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_datatransactions_type_datatransactions_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='Data_balance',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
