# Generated by Django 4.0.1 on 2022-02-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_databundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransactions',
            name='user',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
